# Generated by Django 4.1.6 on 2023-02-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_by',
            field=models.CharField(default='john', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='John', max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Does', max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_name',
            field=models.CharField(choices=[('ROLE_ADMIN', 'admin'), ('ROLE_SUPER_ADMIN', 'surper_admin'), ('ROLE_MANAGER', 'manager'), ('ROLE_ACCOUNTANT', 'comptable'), ('ROLE_COLLECTOR', 'collecteur'), ('ROLE_ANONYME', 'anonyme')], default='ROLE_ANONYME', max_length=150, verbose_name='role name'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.CharField(default='john', max_length=150),
        ),
    ]
