# Generated by Django 4.1.6 on 2023-02-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_added_by_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
