# Generated by Django 4.1.6 on 2023-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_user_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='added_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
