# Generated by Django 4.1.6 on 2023-02-15 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_picture_article_alter_picture_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='article.articles'),
        ),
    ]
