# Generated by Django 4.1.6 on 2023-02-12 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
